name: artifacts example

on: workflow_dispatch

jobs:
  uploadArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Create local file"
        run: echo "Creating local file as artifact" > file.txt
      - uses: actions/upload-artifact@v3
        with:
          name: file
          path: file.txt


  downloadArtifact:
    runs-on: ubuntu-latest
    needs: uploadArtifact
    steps:
      - name: "download file"
      - uses: actions/download-artifact@v3
        with:
          name: file
      - run: cat file.txt