name: Execute tests

on:
  push:
    branches: ["master"]

jobs:
  starts-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: docker-compose-up
        run: |
          ls
          cd src/main/resources/docker-System
          docker-compose up -d

      - name: curls request
        run: curl localhost:8081

      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'adopt'

      - name: execute-maven-tests
        run: | 
          cd ../../../../mvn test