name: Execute tests

on:
  push:
    branches: ["master"]

jobs:
  executeTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run simple command
        run: |
          ls,
          cd src/main/resources/docker-System,
          docker-compose up

      - name: Run two commands
        run: | 
          echo add action,
          echo test