name: Github secrets using environment

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:
      - name: Print secret
        run: |
          echo "APP Secre: ${{ secrets.APP_SECRET }}"